const byId = (id: string): any => document.getElementById(id);

export const els = {
  runSelect: byId('runSelect'),
  toggleJudgeBtn: byId('toggleJudgeBtn'),
  exportFailBtn: byId('exportFailBtn'),
  reloadBtn: byId('reloadBtn'),
  status: byId('status'),
  search: byId('search'),
  filterKind: byId('filterKind'),
  filterLabel: byId('filterLabel'),
  caseCounts: byId('caseCounts'),
  caseList: byId('caseList'),
  detailEmpty: byId('detailEmpty'),
  detailContent: byId('detailContent'),
  activeId: byId('activeId'),
  activeKind: byId('activeKind'),
  humanLabel: byId('humanLabel'),
  humanNotes: byId('humanNotes'),
  saveBtn: byId('saveBtn'),
  saveStatus: byId('saveStatus'),
  questionText: byId('questionText'),
  metaTags: byId('metaTags'),
  metaTickers: byId('metaTickers'),
  metaJudge: byId('metaJudge'),
  timingBlock: byId('timingBlock'),
  timingTotalPill: byId('timingTotalPill'),
  timingRetrieve: byId('timingRetrieve'),
  timingRerank: byId('timingRerank'),
  timingDraft: byId('timingDraft'),
  timingFinal: byId('timingFinal'),
  timingSummary: byId('timingSummary'),
  judgeBlock: byId('judgeBlock'),
  judgePredPill: byId('judgePredPill'),
  judgeIdPill: byId('judgeIdPill'),
  judgeExplanation: byId('judgeExplanation'),
  draftAnswer: byId('draftAnswer'),
  finalAnswer: byId('finalAnswer'),
  chunksReranked: byId('chunksReranked'),
  chunksRetrieved: byId('chunksRetrieved'),
  rerankedEmpty: byId('rerankedEmpty'),
  retrievedEmpty: byId('retrievedEmpty'),
  retrievedDetails: byId('retrievedDetails'),
  retrievedCountPill: byId('retrievedCountPill'),
};

export const state: any = {
  runs: [],
  runDir: null,
  cases: [],
  filtered: [],
  selectedId: null,
  selectedDetail: null,
  saveTimer: null,
  dirty: false,
  showJudge: false,
};
